# Example template to deploy release pipeline
parameters:
  - name: SubscriptionName
    type: string
  - name: EnvironmentName
    type: string
    default: "dev"
  - name: DeployInfra
    type: boolean
    default: true
  - name: TeamName
    type: string
  - name: ProjectName
    type: string
  - name: Location
    type: string
    default: westeurope
  - name: EnvironmentResourceType
    type: string
    default: ""
  - name: EnvironmentTags
    type: string
    default: ""
  - name: LogAnalyticsWorkspaceResourceId
    type: string

jobs:
  - deployment:
    displayName: "${{ parameters.EnvironmentName }}"
    environment:
      name: ${{ parameters.EnvironmentName }}
    ${{ if ne(parameters.EnvironmentResourceType, '') }}:
      resourceType: ${{ parameters.EnvironmentResourceType }}
    ${{ if ne(parameters.EnvironmentTags, '') }}:
      tags: ${{ parameters.EnvironmentTags }}
    variables:
      # Add your variables here.

      # Basics
      - name: DeployInfra
        value: "${{ parameters.DeployInfra }}"
      - name: ResourceGroupName
        value: ${{ parameters.TeamName }}-${{ parameters.ProjectName }}-${{ parameters.EnvironmentName }}
      - name: ResourceTags
        value: "@('BillingIdentifier=$(Tag.BillingIdentifier)'; 'EnvironmentType=${{ parameters.EnvironmentName }}';  'ApplicationName=$(Tag.ApplicationName)'; 'AppTechOwner=$(Tag.AppTechOwner)'; 'ApplicationOwner=$(Tag.ApplicationOwner)'; 'ApplicationID=$(Tag.ApplicationID)'; 'BusinessUnit=$(Tag.BusinessUnit)'; 'CostType=$(Tag.CostType)'; 'Tier=$(Tag.Tier)')"
      - name: Location
        value: ${{ parameters.Location }}

      # AppInsights
      - name: AppInsightsName
        value: ${{ parameters.TeamName }}-${{ parameters.ProjectName }}
      - name: AppInsightsResourceGroupName
        value: $(ResourceGroupName)
      - name: AppInsightsLocation
        value: ${{ parameters.Location }}

      # Log Analytics Workspace
      - name: LogAnalyticsWorkspaceResourceGroupName
        value: "loganalyticsworkspaceresourcegroupname"
      - name: LogAnalyticsWorkspaceName
        value: "loganalyticsworkspacename"

    strategy:
      runOnce:
        deploy:
          steps:
            # Download the artifact
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: "specific"
                project: "projectguid"
                definition: "594"
                buildVersionToDownload: "latestFromBranch"
                branchName: "refs/heads/master"
                artifactName: "azdocs-src"
                targetPath: "$(Pipeline.Workspace)/AzDocs"
              # Call the different tasks you need to be able to deploy your resources
              # Get your log analytics workspace id, output variable is $(LogAnalyticsWorkspaceResourceId)
            - task: AzureCLI@2
              displayName: "Get Log Analytics Workspace Id"
              condition: and(succeeded(), eq(variables['DeployInfra'], 'true'))
              inputs:
                azureSubscription: "${{ parameters.SubscriptionName }}"
                scriptType: pscore
                scriptPath: "$(Pipeline.Workspace)/AzDocs/Log-Analytics-Workspace/Get-Log-Analytics-Workspace-Id-for-Pipeline.ps1"
                arguments: "-LogAnalyticsWorkspaceResourceGroupName '$(LogAnalyticsWorkspaceResourceGroupName)' -LogAnalyticsWorkspaceName '$(LogAnalyticsWorkspaceName)'"
            - task: AzureCLI@2
              displayName: "Create ResourceGroup"
              condition: and(succeeded(), eq(variables['DeployInfra'], 'true'))
              inputs:
                azureSubscription: "${{ parameters.SubscriptionName }}"
                scriptType: pscore
                scriptPath: "$(Pipeline.Workspace)/AzDocs/Resourcegroup/Create-ResourceGroup.ps1"
                arguments: "-ResourceGroupLocation '$(Location)' -ResourceGroupName '$(ResourceGroupName)' -ResourceTags $(ResourceTags)"
            - task: AzureCLI@2
              displayName: "Create AppInsights Resource"
              condition: and(succeeded(), eq(variables['DeployInfra'], 'true'))
              inputs:
                azureSubscription: "${{ parameters.SubscriptionName }}"
                scriptType: pscore
                scriptPath: "$(Pipeline.Workspace)/AzDocs/AppInsights/Create-AppInsights-Resource.ps1"
                arguments: "-AppInsightsName '$(AppInsightsName)' -AppInsightsResourceGroupName '$(AppInsightsResourceGroupName)' -AppInsightsLocation '$(AppInsightsLocation)' -LogAnalyticsWorkspaceResourceId '$(LogAnalyticsWorkspaceResourceId)'"
