[CmdletBinding(DefaultParameterSetName='cidr')]
param (
    [Alias("ResourceGroupName")]
    [Parameter(Mandatory)][string] $AppServiceResourceGroupName,
    [Parameter(Mandatory)][string] $AppServiceName,
    [Parameter()][string] $AccessRestrictionRuleDescription,
    [Alias("IpRangeToWhitelist")]
    [Parameter()][string] $AppServiceDeploymentSlotName,
    [Parameter()][string] $AccessRestrictionAction = "Allow",
    [Parameter()][string] $Priority = 10,
    [Parameter()][bool] $ApplyToAllSlots = $false,
    [Parameter()][bool] $ApplyToMainEntrypoint = $true,
    [Parameter()][bool] $ApplyToScmEntrypoint = $true,

    # Rulename/CIDR/Subnet
    [Parameter()][string] $AccessRestrictionRuleName,
    [Parameter()][ValidatePattern('^$|^(?:(?:\d{1,3}.){3}\d{1,3})(?:\/(?:\d{1,2}))?$', ErrorMessage = "The text '{0}' does not match with the CIDR notation, like '1.2.3.4/32'")][string] $CIDRToWhitelist,
    [Parameter()][string] $SubnetName,
    [Parameter()][string] $VnetName,
    [Parameter()][string] $VnetResourceGroupName
)

#region ===BEGIN IMPORTS===
Import-Module "$PSScriptRoot\..\AzDocs.Common" -Force
#endregion ===END IMPORTS===

# GEEN OPTIES (autogenerated CIDR & autogenerated ACCESSRULENAME o.b.v. CIDR)
# ACCESSRULENAME (met autogenerated CIDR)
# ACCESSRULENAME & CIDR
# CIDR (met autogenerated ACCESSRULENAME)
# SUBNET (met autogenerated ACCESSRULENAME)
# SUBNET & ACCESSRULENAME

Write-Header -ScopedPSCmdlet $PSCmdlet

$AutoGeneratedAccessRestrictionRuleName = $false
if(!$AccessRestrictionRuleName)
{
    $AutoGeneratedAccessRestrictionRuleName = $true
}

if($CIDRToWhitelist -and $SubnetName -and $VnetName -and $VnetResourceGroupName)
{
    throw "You can not enter a CIDRToWhitelist (CIDR whitelisting) in combination with SubnetName, VnetName, VnetResourceGroupName (Subnet whitelisting). Choose one of the two options."
}

# Autogenerate CIDR if no CIDR or Subnet is passed
if(!$CIDRToWhitelist -and (!$SubnetName -or !$VnetName -or !$VnetResourceGroupName))
{
    $response  = Invoke-WebRequest 'https://ipinfo.io/ip'
    $CIDRToWhitelist = $response.Content.Trim() + '/32'
}

# Autogenerate name if no name is given
if(!$AccessRestrictionRuleName -and $CIDRToWhitelist)
{
    $AccessRestrictionRuleName = ($CIDRToWhitelist -replace "\.", "-") -replace "/", "-"
}
elseif(!$AccessRestrictionRuleName -and $SubnetName -and $VnetName -and $VnetResourceGroupName)
{
    $AccessRestrictionRuleName = ToMd5Hash -InputString "$($VnetResourceGroupName)_$($VnetName)_$($SubnetName)_allow"
}

# Fetch Subnet ID when subnet option is given.
if($SubnetName -and $VnetName -and $VnetResourceGroupName)
{
    $subnetResourceId = (Invoke-Executable az network vnet subnet show --resource-group $VnetResourceGroupName --name $SubnetName --vnet-name $VnetName | ConvertFrom-Json).id
}




# Check apply to all slots
if ($ApplyToAllSlots)
{
    $availableSlots = Invoke-Executable -AllowToFail az webapp deployment slot list --name $AppServiceName --resource-group $AppServiceResourceGroupName | ConvertFrom-Json
    if($AppServiceDeploymentSlotName)
    {
        $availableSlots = $availableSlots | Where-Object { $_.name -ne $AppServiceDeploymentSlotName }
    }
}


Add-AccessRestriction -AppType webapp -ResourceGroupName $AppServiceResourceGroupName -ResourceName $AppServiceName -AccessRestrictionRuleName $AccessRestrictionRuleName -CIDRToWhiteList $CIDRToWhiteList -AccessRestrictionAction $AccessRestrictionAction -Priority $Priority -DeploymentSlotName $AppServiceDeploymentSlotName -AccessRestrictionRuleDescription $AccessRestrictionRuleDescription -ApplyToMainEntrypoint $ApplyToMainEntrypoint -ApplyToScmEntrypoint $ApplyToScmEntrypoint

# Apply to all slots if desired
foreach($availableSlot in $availableSlots)
{
    Add-AccessRestriction -AppType webapp -ResourceGroupName $AppServiceResourceGroupName -ResourceName $AppServiceName -AccessRestrictionRuleName $AccessRestrictionRuleName -CIDRToWhiteList $CIDRToWhiteList -AccessRestrictionAction $AccessRestrictionAction -Priority $Priority -DeploymentSlotName $availableSlot.name -AccessRestrictionRuleDescription $AccessRestrictionRuleDescription -ApplyToMainEntrypoint $ApplyToMainEntrypoint -ApplyToScmEntrypoint $ApplyToScmEntrypoint
}

Write-Footer -ScopedPSCmdlet $PSCmdlet