trigger: none
resources:
  - repo: self

steps:
  - checkout: self
    persistCredentials: true
  - task: PowerShell@2
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $sourceBranch = $env:SYSTEM_PULLREQUEST_SOURCEBRANCH.replace('refs/heads/', '')
        Write-Host 'Configuring git author info..' -ForegroundColor Cyan
        git config user.email 'Azure DevOps pipeline'
        git config user.name 'Azure.Devops@pipeline.com'
        Write-Host 'Doing git checkout...' -ForegroundColor Cyan
        git checkout -b $sourceBranch 
      
        . .\Tools\Bicep\Get-BicepMetadata.ps1
        . .\Tools\Bicep\Update-MetadataMarkdown.ps1
        $metadata = Get-BicepMetadata -path '.\src-bicep'
        Update-MetadataMarkdown -Metadata $metadata -DestinationPath '.\Wiki\Azure\AzDocs-v2\Modules'
        
        git add --all
        git diff --quiet && git diff --staged --quiet || git commit --all --message "Updating Documentation [skip azurepipelines]"

        Write-Host "Doing git push.." -ForegroundColor Cyan
        git push --set-upstream origin $sourceBranch
        Write-Host "Done." -ForegroundColor Cyan  